# Generated by Django 5.2.3 on 2025-06-25 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('imagem', models.ImageField(help_text='Faça o upload da imagem do projeto', upload_to='projetos/', verbose_name='Imagem')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('link_online', models.URLField(blank=True, null=True, verbose_name='Link para o projeto online')),
                ('link_github', models.URLField(blank=True, null=True, verbose_name='Link para o GitHub')),
            ],
        ),
    ]
