# Generated by Django 5.2.3 on 2025-06-25 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=200, verbose_name='Cargo')),
                ('nome_empresa', models.CharField(max_length=200, verbose_name='Nome da Empresa')),
                ('icone_empresa', models.ImageField(help_text='Faça o upload do logo/ícone da empresa', upload_to='icones_empresas/', verbose_name='Ícone da Empresa')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('emprego_atual', models.BooleanField(default=False, help_text='Marque esta opção se você ainda trabalha nesta empresa.', verbose_name='Este é o emprego atual?')),
                ('data_fim', models.DateField(blank=True, help_text='Deixe em branco se for o emprego atual.', null=True, verbose_name='Data de Fim')),
                ('descricao', models.TextField(verbose_name='Descrição das Atividades')),
            ],
        ),
    ]
