# Generated by Django 5.2.3 on 2025-06-26 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_experiencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Educacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('instituicao', models.CharField(max_length=200, verbose_name='Instituição / Empresa')),
                ('tipo', models.CharField(choices=[('CURSO', 'Curso'), ('CERT', 'Certificação')], default='CURSO', max_length=5, verbose_name='Tipo')),
                ('data_conclusao', models.DateField(verbose_name='Data de Conclusão')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('link_certificado', models.URLField(blank=True, null=True, verbose_name='Link para o Certificado')),
            ],
        ),
        migrations.CreateModel(
            name='Formacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=200, verbose_name='Curso')),
                ('instituicao', models.CharField(max_length=200, verbose_name='Instituição')),
                ('logo_instituicao', models.ImageField(upload_to='logos_instituicoes/', verbose_name='Logo da Instituição')),
                ('grau', models.CharField(choices=[('Ensino Fundamental', 'Ensino Fundamental'), ('Ensino Médio', 'Ensino Médio'), ('Curso Técnico', 'Curso Técnico'), ('Curso Superior', 'Curso Superior'), ('Especialização', 'Especialização'), ('MBA', 'MBA'), ('Mestrado', 'Mestrado'), ('Doutorado', 'Doutorado')], verbose_name='Grau')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('em_andamento', models.BooleanField(default=False, help_text='Marque esta opção se esta formação ainda não foi concluída.', verbose_name='Em andamento?')),
                ('data_fim', models.DateField(blank=True, help_text='Deixe em branco ou use uma data futura se estiver em andamento.', null=True, verbose_name='Data de Fim (ou Previsão)')),
            ],
        ),
        migrations.CreateModel(
            name='Habilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilidade', models.CharField(max_length=100, verbose_name='Habilidade')),
                ('icone', models.ImageField(upload_to='icones_habilidades/', verbose_name='Ícone da Habilidade')),
                ('tipo', models.CharField(choices=[('HARD', 'Hard Skill'), ('SOFT', 'Soft Skill')], default='HARD', max_length=4, verbose_name='Tipo de Habilidade')),
                ('descricao', models.TextField(blank=True, help_text='Descreva brevemente a habilidade.', null=True, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Lingua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lingua', models.CharField(max_length=100, verbose_name='Língua')),
                ('icone', models.ImageField(upload_to='icones_linguas/', verbose_name='Ícone da Língua')),
                ('nivel', models.CharField(choices=[('Elementar', 'Elementar'), ('Básico', 'Básico'), ('Básico-Intermediário', 'Básico-Intermediário'), ('Intermediário', 'Intermediário'), ('Intermediário-Avançado', 'Intermediário-Avançado'), ('Avançado', 'Avançado'), ('Fluente', 'Fluente'), ('Nativo', 'Nativo')], verbose_name='Nível')),
            ],
        ),
    ]
